apiVersion: v1
kind: Service
metadata:
  name: connector
  namespace: oauth-ms
spec:
  type: ClusterIP
  selector:
    app: connector
  ports:
    - name: http
      port: 8080
      targetPort: 8080
