apiVersion: v1
kind: Service
metadata:
  name: internal-service
  namespace: oauth-ms
spec:
  type: ClusterIP
  selector:
    app: internal-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
